version: '3'
services:
  web:
    build: .
    ports:
    - "8000:3000"
    volumes:
    - .:/kmigrate
    links:
    - postgres
    command: bash -c "export SECRET_KEY_BASE=`rake secret` && rake db:create && rake db:migrate && rake assets:precompile && bundle exec rails s"
    environment:
      - RAILS_ENV=production
      - KMIGRATE_DATABASE_PASSWORD=zW/F,![@9rA(9:,H
      - ITEMS_API=https://api.kktown.com.tw/api/accounts/%s/items?size=100&last_serial_number=%s
      - PROFILE_API=https://api.kktown.com.tw/api/accounts/%s  
      - USERNAME_PROFILE=https://api.carousell.com/api/2.0/username/%s
      - CAROUSELL_PRODUCTS=https://api.carousell.com/api/2.5/products/
  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=zW/F,![@9rA(9:,H
      - POSTGRES_USER=kmigrate
      
